export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ERROR_FETCH_INGREDIENTS = "ERROR_FETCH_INGREDIENTS";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";

export const ORDER_BURGER_SUCCESS = "ORDER BURGER_SUCCESS";
export const ORDER_BURGER_FAIL = "ORDER_BURGER_FAIL";
export const ORDER_BURGER_START = "ORDER_BURGER_START";
export const ORDER_PURCHASING_INIT = "ORDER_PURCHASING_INIT";
export const ORDER_INITIATE_PLACING = "ORDER_INITIATE_PLACING";
export const ORDER_INITIATE_LOAD = "ORDER_INITIATE_LOAD";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ORDER_LOADING_START = "ORDER_LOADING_START";
export const ORDER_LOADING_SUCCESS = "ORDER_LOADING_SUCCESS";
export const ORDER_LOADING_FAIL = "ORDER_LOADING_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_AUTH = "AUTH_INITIATE_AUTH";
export const AUTH_INITIATE_AUTOLOGIN = "AUTH_INITIATE_AUTOLOGIN";
