export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const ERROR_FETCH_INGREDIENTS = 'ERROR_FETCH_INGREDIENTS';

export const ORDER_BURGER_SUCCESS = 'ORDER BURGER_SUCCESS';
export const ORDER_BURGER_FAIL = 'ORDER_BURGER_FAIL';
export const ORDER_BURGER_START = 'ORDER_BURGER_START';
export const ORDER_PURCHASING_INIT = 'ORDER_PURCHASING_INIT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';